### ISSUE TITLE
Add licensing information in all source files

### ISSUE THREAD

**Issue by valeriabarra** [csrc-sdsu/mole#13]
Licensing information should be added at the top of all of the source files. It can be a summarized version, but it should be there.

**Comment by aneeshs1729** [comment]
I'd like to take this issue.

**Comment by aneeshs1729** [comment]
I plan to add the following licensing information to the files. The exact text is - 
### MOLE is distributed under a GNU General Public License; please refer to the LICENSE file in for more details.

Based on reading the above issue, I am supposed to add it to "all the source files" (not just the files that i have added/modified).

I am going ahead and modifying the same. Please let me know if this is not what i am supposed to be doing.

**Comment by jbrzensk** [comment]
```
// SPDX-License-Identifier: GPL-3.0-only
// 
// Copyright 2008-2024 San Diego State University (SDSU) and Contributors 
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// LICENSE file or on the web GNU General Public License 
// <https://www.gnu.org/licenses/> for more details.
//
// ------------------------------------------------------------------------
```

The format is given at the very end of the LICENSE file. SPDX-License-Identifier is if we want to incorporate it later, one line that can be read by other things. https://spdx.dev/learn/handling-license-info/

**Comment by jbrzensk** [comment]
The comment style should match the existing comment structure of the file this is put in.
