### ISSUE TITLE
Implement decomposition in parabolic1.m

### ISSUE THREAD

**Issue by jbrzensk** [csrc-sdsu/mole#14]
Implement the change given in the following lines in examples_MATLAB/parabolic1d.m

https://github.com/csrc-sdsu/mole/blob/c78ef4680da883d8a7f98b0d93ab77f4248ab572/examples/examples_MATLAB/parabolic1D.m#L63-L65

**Comment by aneeshs1729** [comment]
Do you know how I can assign myself to this Issue? I want to take this issue.

**Comment by jbrzensk** [comment]
It would also be nice to add a comment/explanation of WHY decomposition is used in the code.
