### ISSUE TITLE
[Discussion] Proposed Directory Structure

### ISSUE THREAD

**Issue by pritkc** [csrc-sdsu/mole#16]
Current dir in prod: [directory_structure.txt](https://github.com/user-attachments/files/17640420/directory_structure.txt)

To make our project easier to navigate and more organized, I’m proposing a directory restructure that aligns with industry standards. Key ideas:
- All manuals, guides, and images under docs, with clear subfolders (like manuals, api, and images).
- Group src by language (e.g., mole_C++ and mole_MATLAB) and within each, organize files by functionality (like operators, solvers, utils).
- Have dedicated examples and tests folders with language-specific subfolders.

- A proposed structure inspired from the LIBCEED repo:

![image](https://github.com/user-attachments/assets/13602df4-dae2-4aa6-a00c-2a6a0744d91e)

Open to thoughts and feedback!

CC @valeriabarra

**Comment by valeriabarra** [comment]
Hi @pritkc, thank you for creating the Issue and outlining the proposed structure.

I agree, it would be better to move to a different model. I like libCEED's organization.

Just one minor comment. Perhaps I would remove the "manuals" subdirectory, as all those Markdown files there, including guides, will constitute the main User Manual anyways (eventually we won't have the scattered PDF files anymore. Their source will be included in the User Manual content).

Any objections/comments on the proposed structure?

cc:  @jbrzensk

**Comment by jbrzensk** [comment]
I'm a little confused. Outside of the documents folder, isn't the proposed structure the current folder structure? 

I like the doc folder suggestions.

**Comment by valeriabarra** [comment]
Okay. Sounds good. @pritkc you can proceed with the proposed outlined `docs` structure (I would just remove `manuals`). 

Please create a PR when ready with the new file organization and, in the PR description, use verbiage that will link/pair it to this Issue, such as 

> Will close #16

So that GH automatically associates the PR to this Issue. Thanks!

**Comment by valeriabarra** [comment]
Hi @pritkc , thank you for your work. 

It looks good for me now. Eventually, as discussed, we will remove the "manuals" subdirectory, as those PDF files will be embedded in the documentation/User Manual source anyways. 
You can go ahead. Thank you.
